[package]
name = "echor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
anyhow = "1"
assert_cmd = "2"
predicates = "3"
pretty_assertions = "1"
